### PR TITLE
Fix nested directory on windows

### PR DESCRIPTION
**Pull request by anshulrgoyal**
The action uses the backslash (\) instead of slash (/) for the key on windows causing incorrect upload on S3

### CODE REVIEW

**Comment by davidjreese** [comment]
Is this ever going to be merged? I am trying to use this but running into the slash issue. It looks like this has been open and ready to merge for a year.

**Comment by shallwefootball** [comment]
fix https://github.com/shallwefootball/upload-s3-action/releases/tag/v1.3.2

**Comment by Froxz** [comment]
@shallwefootball I get error: `TypeError: slash is not a function`

**Comment by mpszymanski** [comment]
> @shallwefootball I get error: `const sourceDir = slash(path.join(process.cwd(), SOURCE_DIR)); TypeError: slash is not a function`

+1

**Comment by shallwefootball** [comment]
@Froxz @mpszymanski fix https://github.com/shallwefootball/upload-s3-action/releases/tag/v1.3.3 🙏

**Pull request closed without merging**
