### PR TITLE
Add Region: Resolve missing Key fatal error

### PR DESCRIPTION
**Pull request by golden-protocol**
https://github.com/shallwefootball/upload-s3-action/issues/27
https://github.com/shallwefootball/upload-s3-action/issues/26

### CODE REVIEW

**Comment by balexander** [comment]
Thanks for this fix. Any idea when this will get merged in?

**Comment by drpym** [comment]
No idea. But if you need something for s3. I can post the workaround I have been using. The aws-sdk is included in actions so you can just use the regular sdk.

**Comment by balexander** [comment]
@drpym Thanks, I'd appreciate if you could post the work around

**Comment by drpym** [comment]
@balexander  something to note: If you ubuntu-latest it will error out. 
set 
```
  os: [ubuntu-18.04]
```
sorry for another message, just wanted to make sure you saw this.

**Comment by woodyhayday** [comment]
Just to add here, changing `os` to `[ubuntu-18.04]` and using the mod @golden-protocol mentions:
```
  - name: upload
     run: AWS_ACCESS_KEY_ID=${{secrets.AWS_ACCESS_KEY}} AWS_SECRET_ACCESS_KEY=${{secrets.AWS_SECRET_KEY}} aws s3 cp ./myfile.txt s3://${{bucketName}}/myFile.txt
     working-directory: /dir/where/file/is/
```
... works for me. 

Though I'm not certain this, (or #27), is a region bug, as I get it with one of two buckets in the same region. I wondered if it's because of the public/no public access?:
Screenshot 2021-11-01 at 15 01 57

... either way, thanks for the helpful workaround.

**Pull request closed without merging**
